### ISSUE TITLE
add asterisks (*) to the mandatory fields for filling

### ISSUE THREAD

**Issue by karbyshevds** [odahu/odahu-ui#17]
The list of forms and required fields for each form.

**ODAHU Entities:**
- Connections
- Model Trainings
- Model Packagings
- Model Deployments

- ## **_Connections:_**
    `ID`, `Type` fields for **all connections**.
    ![image](https://user-images.githubusercontent.com/49116723/138065517-a043ba20-f2ba-4bec-b6e9-1216d5fd74dd.png)

    -  **git** type:
    `Git SSH URL`, `SSH private key`
    ![image](https://user-images.githubusercontent.com/49116723/138065919-6137f9be-969d-4228-ae16-bcef2511e525.png)

    - **docker** type:
    `URI`, `Username`, `Password`
    ![image](https://user-images.githubusercontent.com/49116723/138066500-8496e69d-94dd-4e96-8389-46093be34e83.png)

    - **gcs** type:
    `Project`, `URI`, `Service account secret`
    ![image](https://user-images.githubusercontent.com/49116723/138066844-a9a603c7-2480-48b7-9791-6bd4d6a97c98.png)

    - **azureblob** type:
    `URI`, `SAS Token`
    ![image](https://user-images.githubusercontent.com/49116723/138067096-1d8594b3-3035-4968-addb-deb4268cdc97.png)

    -  **s3** type:
    `URI`, `Region`, `Access Key ID`, `Access Key Secret`
    ![image](https://user-images.githubusercontent.com/49116723/138065799-41aaf2f5-9bb3-4846-a8e2-a72a30d859a5.png)

    - **ecr** type
    `URI`, `Access Key ID`, `Access Key Secret`
    ![image](https://user-images.githubusercontent.com/49116723/138068840-a14411b3-773d-4787-8bf8-7f92e5bc24f2.png)

- ## **_Model Training_**:
    - **Metadata** step:
    `ID`, `Model name`, `Model version`, `Toolchain`, `Output connection`
![image](https://user-images.githubusercontent.com/49116723/139666566-2d61062f-966f-496d-b5c3-4611a7ab8966.png)
    - **Specification** step:
    `Entrypoint`
    if **Data section** is specified, for every data entry,
the `Connection ID` and `Target Path` are required fields:
    ![image](https://user-images.githubusercontent.com/49116723/138071851-66943f8b-0dcb-4c0b-9884-e7d2dd67b976.png)
    if **Environment variables** or **Hyper Parameters** are specified,
for every entry the `Name` and `Value` are required fields:
![image](https://user-images.githubusercontent.com/49116723/138072357-e2242f9d-4bfa-4077-bcf6-75d5fef12cfb.png)
![image](https://user-images.githubusercontent.com/49116723/138072748-56e3262f-26b2-4fa6-bb61-97fc26882fd1.png)

- ## **_Model Packaging_**:
    - **Metadata** step:
    `ID`, `Output Connection ID`, `Integration`
    ![image](https://user-images.githubusercontent.com/49116723/138078582-4e95f04c-9274-48ce-9498-c6270eda63df.png)
    - **Specification** step:
    `Artifact`
    if **Target** entry is specified, `Name` and `Connection ID` are required fields.
    if **Arguments** entry is specified, `Name` and `Value` are required fields.
    ![image](https://user-images.githubusercontent.com/49116723/138079182-322c55d6-3a95-481a-97cd-bdb7753e6bf9.png)

- ## **_Model Deployment_**:
    - **Metadata** step:
    `ID`, `Image pull connection ID`
    ![image](https://user-images.githubusercontent.com/49116723/138081953-4e2ac6fd-33fa-4543-ad43-3985a307a80d.png)
    - **Specification** step:
   ` Predictor`, `Docker image`, `Minimum replicas`, `Maximum replicas`
    ![image](https://user-images.githubusercontent.com/49116723/138082875-cedb2c58-8c96-48ad-ab40-daa9c5fc7ba8.png)

**Comment by alinaignatiuk** [comment]
Step 1. @BPylypenko will create the list of forms and required fields for each form
Step 2. @GennadiyShpak will add asterisks to the fields in forms as per the list from Step 1.

**Comment by BPylypenko** [comment]
Also,
## Model Training
`Algorithm source settings`: 
`VCS Connection` Algorithm source:
![image](https://user-images.githubusercontent.com/49116723/152154304-4fbe9406-f891-4ff4-bef1-71227b12386b.png)


`Object Storage` Algorithm source:
![image](https://user-images.githubusercontent.com/49116723/152154141-cbfabc2a-3c74-4e60-b5aa-163a444e6170.png)


## Model Deployment
The `Maximum replicas`, `Minimum replicas` are not required.
