### ISSUE TITLE
[Need to reproduce] Makes changes to diagrams of dashboard

### ISSUE THREAD

**Issue by karbyshevds** [odahu/odahu-ui#23]
1. the diagrams shouldn't go out their frames
1. add a legend for pie charts
1. take out axes for pie charts
1. the diagrams at `dashboard` doesn't update after making changes at another browser tab.
![image](https://user-images.githubusercontent.com/763662/84964616-3a5fae00-b115-11ea-8c7f-7520fe451a09.png)

**Comment by BPylypenko** [comment]
Already fixed in [set of WEB ODAHU UI improvements](https://github.com/odahu/odahu-ui/pull/120) PR.
related issue: [Set of WEB ODAHU UI improvements ](https://github.com/odahu/odahu-ui/issues/104)
