### ISSUE TITLE
help asks to pass SAS Token/service account whereas it needs a base64 token

### ISSUE THREAD

**Issue by BPylypenko** [odahu/odahu-ui#43]
**To Reproduce**
1. go to `Connections` panel 
1. press `+ New` button
1. select `Type` as `azureblob`
1. fill in required fields and press `NEXT`

**Expected behavior**
you should be asked to pass `keySecret` which is in based64 format

**Actual behavior**
you are asked for SAS Token on `Azure`:
![image](https://user-images.githubusercontent.com/49116723/93521639-0759d000-f939-11ea-9670-8fd11e70b5b7.png)

and for service account on `GCP` type: `gcs`:
![image](https://user-images.githubusercontent.com/49116723/93755838-b2ee7300-fc0c-11ea-820a-9ecc69e3c4e8.png)

and update comment for `ecr` and `s3` types on `AWS`:
![image](https://user-images.githubusercontent.com/49116723/93761894-4167f200-fc17-11ea-809e-5b914030ec1d.png)

**Comment by keshamin** [comment]
Fixed with #46
