### ISSUE TITLE
add selectors for entity tabs: `VIEW`, `EDIT`, etc.

### ISSUE THREAD

**Issue by BPylypenko** [odahu/odahu-ui#99]
**Description**
To make tabs of entities `entity` and `entity type` independent there is a need to add selectors like `id` or `name` for tabs of entities (`VIEW`, `EDIT`, `YAML`, `LOGS`, etc.)

**Attachments**
![image](https://user-images.githubusercontent.com/49116723/114692105-fcc1b680-9d20-11eb-9b71-8703e2a22e76.png)

**Comment by keshamin** [comment]
Use XPath selector for it: `//span[@class="MuiTab-wrapper" and text()="Edit"]`
![Uploading xpath_selectors.gif…]()
